### ISSUE TITLE
Unhandled exception warning even if calling method has @Throws annotation

### ISSUE THREAD

**Issue by grote** [thirdegg/lint-rules#1]
First of all, great project that I consider very underrated and unfortunately not widely known. Thanks a lot for it!

The only issue I have with the linter is that it complains about unhandled exceptions of `X` for method calls that happen inside a method that is annotated to throw `X`. Here's a small example:

```kotlin

    @Throws(IOException::class)
    fun doesIO() {
        openFile()  // <-- I get a warning here
    }

    @Throws(IOException::class)
    fun openFile() {
        fooBar()
    }

```

Would be great if this could get fixed in the next version!

**Comment by grote** [comment]
What is strange is that if I try to add a test for that to `CheckedExceptionsUnitTest`, I do not get any warnings for it. However, the linter inside Android Studio complains about the unchecked exception for the same test. It is using `0.0.4-alpha` through `lintChecks` in `build.gradle` and there doesn't see to be any changes to master since then.

**Comment by thirdegg** [comment]
Thank you for your positive feedback. I fixed this in version 0.0.5-alpha. The problem was that in tests the root of the function was `UAnnotationMethod`, while in real projects it was `UMethod`.

I also rewrote the expression search logic a little. So new bugs are possible :)

**Comment by grote** [comment]
Awesome, thanks a lot!

However, the problem doesn't seem to be fixed for me. Here's a real life example (dependency update not pushed, yet) where the linter is complaining about an unchecked exception: https://github.com/stevesoltys/seedvault/blob/develop/app/src/main/java/com/stevesoltys/seedvault/plugins/saf/DocumentsStorage.kt#L135 `getSetDir()` is defined above and also has a `@Throws` annotation, so when calling this in `getKVBackupDir()`, I still get a warning.

Maybe you can check out this code and see why that happens?

**Comment by grote** [comment]
Actually, it seems the lint plugin version bump didn't get applied immediately. Now after some time with a restarted IDE, it seems that the issue has indeed been fixed.

**Comment by thirdegg** [comment]
Yes, android studio for some reason does not load the new version after changing the version in the dependencies. To make it work need to do `Build> Clear Project`. I added information in `README.md` about this.
