### ISSUE TITLE
Does not specify the Lint API version it was compiled with

### ISSUE THREAD

**Issue by grote** [thirdegg/lint-rules#3]
If I run lint on command line or CI, I get the following warning:

---

Lint found an issue registry (com.thirdegg.lintrules.android.LintRulesRegistry) which did not specify the Lint API version it was compiled with.

This means that the lint checks are likely not compatible.

If you are the author of this lint check, make your lint IssueRegistry class contain
  `override val api: Int = com.android.tools.lint.detector.api.CURRENT_API`
or from Java,
  `@Override public int getApi() { return com.android.tools.lint.detector.api.ApiKt.CURRENT_API; }`

If you are just using lint checks from a third party library you have no control over, you can disable these lint checks (if they misbehave) like this:

    android {
        lintOptions {
            disable "CheckedExceptions"
        }
    }

**Comment by thirdegg** [comment]
Added in `0.0.7-beta`
